lexer grammar LumaLexer;

MODULE : 'module';
MAIN : 'main';
CONST : 'const';
VAR : 'var';
IF : 'if';
ELSE : 'else';
PRINT : 'print';
FLOAT_TYPE : 'float';
BOOL_TYPE : 'bool';
TRUE : 'true';
FALSE : 'false';
GE : '>=';
EQ : '==';
ASSIGN : '=';
COLON : ':';
SEMI : ';';
LPAREN : '(';
RPAREN : ')';
LBRACE : '{';
RBRACE : '}';
COMMA : ',';
fragment DIGIT : [0-9];
fragment LETTER : [a-zA-Z_];
FLOAT_LITERAL : DIGIT+ '.' DIGIT+;
INT_LITERAL : DIGIT+;
STRING_LITERAL : '"' ~["\r\n]* '"';
ID : LETTER (LETTER | DIGIT)*;
WS : [ \t\r\n]+ -> skip;